export default {
  name: 'ng-yunzai',
  description: '',
  tags: ['NG-YUNZAI'],
  version: '0.0.0',
  scripts: {
    ng: 'ng',
    start: 'ng serve',
    build: 'ng build',
    test: 'ng test',
    lint: 'ng lint',
    e2e: 'ng e2e'
  },
  private: true,
  dependencies: {
    '@angular/animations': '^17.1.0',
    '@angular/common': '^17.1.0',
    '@angular/compiler': '^17.1.0',
    '@angular/core': '^17.1.0',
    '@angular/forms': '^17.1.0',
    '@angular/platform-browser': '^17.1.0',
    '@angular/router': '^17.1.0',
    rxjs: '^7.8.1',
    tslib: '^2.6.2',
    'zone.js': '^0.14.3',
    '@yelon/theme': '~17.0.3',
    '@yelon/abc': '~17.0.3',
    '@yelon/chart': '~17.0.3',
    '@yelon/acl': '~17.0.3',
    '@yelon/auth': '~17.0.3',
    '@yelon/cache': '~17.0.3',
    '@yelon/mock': '~17.0.3',
    '@yelon/form': '~17.0.3',
    '@yelon/bis': '~17.0.3',
    '@yelon/bcs': '~17.0.3',
    '@yelon/socket': '~17.0.3',
    '@yelon/util': '~17.0.3',
    '@yelon/testing': '~17.0.3',
    'ng-zorro-antd': '^17.1.0',
    '@stomp/rx-stomp': '^2.0.0',
    '@stomp/stompjs': '^7.0.0',
    'ng-antd-color-picker': '^0.0.2',
    ajv: '^8.12.0',
    'ajv-formats': '^2.1.1',
    'date-fns': '^2.16.1',
    '@angular/cdk': '^17.0.0'
  }
};
