name: Deploy

on: push


jobs:
  website:
    if: "startsWith(github.event.commits[0].message, 'release')"
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - run: yarn install

      - name: build
        run: |
          yarn run site:build:ssr
          cp ./src/dist/browser/index.html ./src/dist/browser/404.html
          cp ./Dockerfile.docs ./src/dist/browser/Dockerfile.docs
          cp -r ./_nginx/ ./src/dist/browser/_nginx

      - name: deploy-to-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./src/dist/browser

      - name: deploy-to-surge
        uses: dswistowski/surge-sh-action@v1
        with:
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
          domain: https://ng-yunzai-doc.surge.sh
          project: ./src/dist/browser
