name: Deploy

on: push

jobs:
  website:
    if: "startsWith(github.event.commits[0].message, 'release')"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install

      - name: build
        run: |
          npm run site:build
          cp ./src/dist/browser/index.html ./src/dist/browser/404.html
          cp ./Dockerfile.docs ./src/dist/browser/Dockerfile.docs
          cp -r ./_nginx/ ./src/dist/browser/_nginx

      - name: deploy-to-gh-pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./src/dist/browser
        with:
          emptyCommits: false

      - name: deploy-to-surge-pre
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: '/yelon/'
          replace: '/'
          include: '\.html$'

      - name: deploy-to-surge
        uses: dswistowski/surge-sh-action@v1
        with:
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
          domain: https://ng-yunzai-doc.surge.sh
          project: ./src/dist/browser
