name: GiteeMirror

on: push

jobs:
  to_gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitee.com:hbyunzai/yelon.git
          ssh_private_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
